### PR TITLE
Retrieve MSVC version from cl.exe

### PR DESCRIPTION
**Pull request by bernhardmgruber**
This PR lets the ctest script retrieve the MSVC version from cl.exe instead of by compiling `./cmake/msvc_version.c`, which has been deleted in #290.

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
I see the MSVC version strings appearing in cdash :)

**Comment by amadio** [comment]
You know CMake has `CMAKE_CXX_COMPILER_VERSION`, right? :-)

**Comment by bernhardmgruber** [comment]
> You know CMake has `CMAKE_CXX_COMPILER_VERSION`, right? :-)

Yes, but does it have that variable in the dashboard client script for ctest? ;-D

Edit: just tried it, the variable is empty in inside `test.cmake`.

**Comment by amadio** [comment]
Yeah, I forgot that I actually detect this information using `cmake --system-information` in `veccore/cmake/TestVecCore.cmake`... We can copy that piece of code for Vc's `test.cmake`, because that works for all compilers, not just MSVC.

**Comment by bernhardmgruber** [comment]
I would prefer my simple fix for this PR. But we can sure consider simplifying `test.cmake` a lot by copying from veccore in a subsequent PR.

**Pull request merged**
