### PR TITLE
CMake buildsystem fixes and submodule support

### LINKED ISSUE #188: Using Vc as CMake subproject
| Vc version / revision | Operating System |
|-----|-----|
| master-branch | Linux |

## Background

This is slightly related to #184, but seeing as I have a concrete use case in mind, I decided to put it into a different issue.

I like the [simd proposal](https://wg21.link/p0214) and my project is in development state, so I'm OK with using unstable master branch. Git submodules seem like the easiest solution. I'm also using CMake, so my hope was that a simple `add_subdirectory` should suffice. This brings me to the problem.

## Problem

CMakelists.txt in Vc root directory uses `CMAKE_SOURCE_DIR`:
https://github.com/VcDevel/Vc/blob/master/CMakeLists.txt#L8
https://github.com/VcDevel/Vc/blob/master/CMakeLists.txt#L185
https://github.com/VcDevel/Vc/blob/master/CMakeLists.txt#L312
This means that if I have Vc cloned somewhere in `myproject/external/Vc`, Vc's CMakelists.txt will search for Vc-specific CMake modules in `myproject/cmake` rather than `myproject/external/Vc/cmake`. Using `CMAKE_CURRENT_SOURCE_DIR` in all three places seems to solve the problem.

Again, I can create a small PR if you like.

Thanks,
Tom

### PR DESCRIPTION
**Pull request by milianw**
One small warning fix for the CMP0071 policy. Then a larger patch that adds `Vc_submodule.cmake` to fix #188 for the 1.4 branch.

### CODE REVIEW

**Comment by mattkretz** [comment]
Thanks @milianw! I'll look at it after vacations

**Comment by milianw** [comment]
I believe there's some more work required here, esp. in regard to #230. I have some code on my windows partition which I'll send in for review later.

I can't make sense of the travis build error though. From what I understand, the `if (POLICY ...)` pattern should work even on older cmake versions, but the build errors on travis seem to indicate the opposite?

**Comment by milianw** [comment]
Ah, no - some tests are now failing, the cmake issue has been resolved after all. I'll have to investigate whether this is due to my CMake changes...

**Comment by amadio** [comment]
Using as a submodule has been fixed in #271. Please open a new merge request if some of these changes are still needed.

**Pull request closed without merging**
