### PR TITLE
[WIP] More SimdArray operators

### PR DESCRIPTION
**Pull request by chr-engwer**
implement missing mathematical operators on the `SimdArray`, see #75

### CODE REVIEW

**Comment by mattkretz** [comment]
Thanks. The `sqrt` implementation is fine. The test is not, though. The best way to test this is actually to go to `tests/math.cpp` and extend the list of types for the `testSqrt` test to include a few `SimdArray` instantiations.

**Comment by chr-engwer** [comment]
OK. I was unsure how you intended the structure f the tests, thus my idea of a proper fix would have involved factoring out the arithmetic tests, but this seems far easier.

**Comment by mattkretz** [comment]
It's all growing. When I initially wrote the math tests I didn't think about `SimdArray` coming around. But the test framework made it really easy to extend. If only compilation time wouldn't suffer so badly...

**Comment by chr-engwer** [comment]
In that case factoring out the tests might actually be the better idea, but I doubt I have the time for this, so I'll just add it to math.cpp :smiley:

**Comment by chr-engwer** [comment]
It is a bit tricky to get the tests for `SimdArray` into `math.cpp`. Currently the old interfaces already fail. Some due to missing implementations of further functions, but some due to strange errors in `Vector`.

I'll push the current state and try to keep as short as possible, so that you might perhaps reproduce the error.

**Comment by mattkretz** [comment]
OK, please do. I'll take a look what is going on.

**Comment by chr-engwer** [comment]
When compiling `make -C test math_scalar` I have basically two errors... it seems that the definition of frexp ad ldexp is broken. The forward to the underlying `Vector` does not work.
```
Vc/common/simdarrayhelper.h:82:37: error: no matching function for call to 'frexp(const Vc_1::Vector<double, Vc_1::VectorAbi::Scalar>&, Vc_1::Vector<int, Vc_1::VectorAbi::Scalar>*)'
Vc/common/simdarrayhelper.h:83:37: error: no matching function for call to 'ldexp(const Vc_1::Vector<double, Vc_1::VectorAbi::Scalar>&, const Vc_1::Vector<int, Vc_1::VectorAbi::Scalar>&)'
Vc/common/simdarrayhelper.h:82:37: error: no matching function for call to 'frexp(const Vc_1::Vector<float, Vc_1::VectorAbi::Scalar>&, Vc_1::Vector<int, Vc_1::VectorAbi::Scalar>*)'
Vc/common/simdarrayhelper.h:83:37: error: no matching function for call to 'ldexp(const Vc_1::Vector<float, Vc_1::VectorAbi::Scalar>&, const Vc_1::Vector<int, Vc_1::VectorAbi::Scalar>&)'
```

When I compile `make -C test math_sse` I get an additional error, that data0 and data1 are not defined in `Vc_1::SimdArray<int, 4ul, Vc_1::Vector<int, Vc_1::VectorAbi::Sse>, 4ul>`, so it seems, that in this case the specialization picks the wrong version?!

**Comment by chr-engwer** [comment]
OK, I looked into it again I now I realized what the problem is. Actually there are two problems in the current approach for `SimdArray`.

  1. the `fromOperator` unpacks all parameters, which transforms the second parameter of `frexp` - a `SimdArray<int,...>` into a `Vector<int>`. Now it doesn't match the interface definition.
  1. the second problem is that even, if we don't unpack it, it doesn't work anymore, because `frexp` for `Scalar` expects a `SimdArray<int,1>`, while `frexp` fro `SSE` expects `SimdArray<int,2> and what we actually have is a `SimdArray<int,N>` with arbitrary length.

In my opinion, we would have to slice the `SimdArray`, but I have currently no clue, split the the `SimdArray<int,N>` into different `SimdArray<...>` objects with sizes which match the expected size for the underlying `double_v` we want to operator on.

**Comment by mattkretz** [comment]
Ah yes, of course. One of those last-minute API changes before the release...

Either `fromOperator` must become smarter and notice at what point it has to stop unwrapping `SimdArray` or we need some annotation to specify how far to unwrap. I'd have to look more closely at the code to decide what I'd do. Feel free to stop there unless you want to see it through now. :)

**Comment by chr-engwer** [comment]
Up to now I still not understand the `SimdArray` in all details, so I'll just wait until you have a proper solution. The branch works for me, as long as I don't try to run the tests. I'll better start using the code an add more missing operators. I think I will only need unary operators and these should work without problems.

**Comment by mattkretz** [comment]
Sure, I'll take it. Thanks for your effort so far!

**Comment by chr-engwer** [comment]
I added some helper macros and implemented all math operators I found in scalar/math.h also for SimdArray. There is still the issue with binary operators taking a SimdArray and an integer-array.

**Comment by mattkretz** [comment]
How do you want to proceed? I could take over, rebase onto current master and get it ready, unless you prefer to finish it yourself.

**Comment by chr-engwer** [comment]
The remaining part is something, I'd consider out-of-bounds right now, as it would require too much time, which I don't have. This is a problem that was already present before my changes, it is just that the new test revealed it.

I'd say you continue from here.

Btw. why do you want to rebase/did rebase the other branch. In our experience in DUNE keeping branches as they are helps structuring the work. Either the rebase works directly, the your merge commit is empty, so no harm done. Or you have conflicts, the it is often much more work to fix them in the rebase than in an additional merge commit (just my 2 cents).

**Comment by mattkretz** [comment]
on rebasing:
I find it much easier to go through the commit history with a linear history. Especially something like `git diff HEAD~<n>` can become incomprehensible (unless you are a git guru) quickly. That's why I like to reduce the number of merge commits to the minimum.
Basically, if rebasing results in a major merge orgy then it's certainly not worth it.

**Comment by chr-engwer** [comment]
I rebased and pushed an additional change (	add min/max for SimdArray)

**Comment by mattkretz** [comment]
Thanks. I already started work on it locally (but then got sick...). I'll make sure it doesn't get lost.

**Comment by mattkretz** [comment]
Done. See #75

**Pull request closed without merging**
