### PR TITLE
Fixing msvc

### PR DESCRIPTION
**Pull request by hkaiser**
This PR proposes some changes to enable compilation using MSVC. It also adds a new algorithm `simd_for_each_n`.

The main change is related to `min()` and `max()` which could be defined as macros. The change protects any use of either of those symbols from being macro expanded.

### CODE REVIEW

**Comment by mattkretz** [comment]
Thanks a lot. I prefer to merge the `simd_for_each_n` addition directly to master.

The MSVC min/max workaround looks scary. What is it needed for? ADL issues? I see you did a complete search and replace, changing some unrelated comments on the way. Would you be able to reduce the changes to the code where it's actually needed?

In the meantime I'll get my MSVC VM up and running again, so I can finally work on integration of the branch.

**Comment by hkaiser** [comment]
MSVC defines `min()` and `max()` macros. This interferes with any token sequence which could be possibly expanded as such. Yah, that's awful, I know. Sorry for changing the comments as well, that was unintentional - I'll try to go over the changes one more time.

**Comment by mattkretz** [comment]
OK, the macros. I got rid of them this way:
https://github.com/VcDevel/Vc/blob/mkretz/gh-119_port_to_Windows_and_MSVC/cmake/VcMacros.cmake#L309
Would you accept a "solution" that includes the following in a central Vc header:
```cpp
#ifndef NOMINMAX
#error "Vc can only be used if you compile with the NOMINMAX macro defined."
#endif
```

**Comment by hkaiser** [comment]
Sure, but that does not seem to be a valid move for a library to be used in arbitrary contexts - at least it's not a solution for us - YMMV.

**Comment by hkaiser** [comment]
> OK, the macros. I got rid of them this way:
https://github.com/VcDevel/Vc/blob/mkretz/gh-119_port_to_Windows_and_MSVC/cmake/VcMacros.cmake#L309

Hmm, why did I have problems, then?

**Comment by mattkretz** [comment]
I fully understand your point. However, how should users be able to use Vc's min and max functions if the macros are defined? They'll have to use parens, then too, disabling ADL at the same time? My view here is that MSVC users are screwed by their compiler anyway, I'll just have to help them a bit to get sane behavior.

> Hmm, why did I have problems, then?

I have no idea. Did you see the problems when compiling Vc itself or only when using it in HPX? If the latter, then you need to do `add_definitions(${Vc_DEFINITIONS})` in the HPX cmake scripts (or something more fine-grained).

**Comment by hkaiser** [comment]
> Did you see the problems when compiling Vc itself or only when using it in HPX

I was seeing it while compiling Vc itself.

**Comment by mattkretz** [comment]
OK, I still don't have my MSVC VM up. I'll see whether I can reproduce.
BTW, 64-bit or 32-bit build? My understanding is, that 32-bit builds still break horribly.

**Comment by hkaiser** [comment]
> BTW, 64-bit or 32-bit build? 

This was a 64Bit build.

**Comment by mattkretz** [comment]
I guess this PR closed because I closed the feature branch it referenced?
I still have it on my backlog - can't reopen it here.

**Comment by mattkretz** [comment]
I merged the `simd_for_each_n` commit, thanks.
I tried to merge your min/max change, but it broke too much for GCC and Clang (and I didn't even test ICC). Now, Vc will just `#undef` min/max and `#define NOMINMAX` in its headers. This isn't nice, but I think this is as close to good as I can get here.

**Pull request closed without merging**
